query getLastGameWaitingForPlayers {
    getLastGameWaitingForPlayers{
        id
        connectedPlayers{
            connectedGamePosition
            username
        }
        host{
            connectedGamePosition
            username
        }
        state
        turns{
            lastRoll
            nextPlayer{
                connectedGamePosition
                username
            }
        }
        openedSession{
            id
            createdAt
        }
    }
}