query getLastTurn {
    getLastTurn{
        lastRoll
        nextPlayer{
            connectedGame{
                id
                playersOrderedByPosition{
                    number
                }
                state
                openedSession{
                    id
                    createdAt
                }
                inviteCode
            }
            connectedGamePosition
            username
            createdGame{
                id
                playersOrderedByPosition{
                    number
                }
                state
                openedSession{
                    id
                    createdAt
                }
                inviteCode
            }
        }
    }
}