query me {
    me{
        connectedGame{
            id
            playersOrderedByPosition{
                number
            }
            state
            turns{
                lastRoll
            }
            openedSession{
                id
                createdAt
            }
            inviteCode
        }
        connectedGamePosition
        username
        createdGame{
            id
            playersOrderedByPosition{
                number
            }
            state
            turns{
                lastRoll
            }
            openedSession{
                id
                createdAt
            }
            inviteCode
        }
    }
}